### ISSUE TITLE
Проверить ДЗ №5 Сервис такси

### ISSUE THREAD

**Issue by sgv1995** [sgv1995/taxi#1]
@coursar, загрузил задание №5 на проверку.

**Comment by sgv1995** [comment]
@coursar, Здравствуйте Ильназ. Исправил задание, вынес логику расчёта в отдельный класс. После исправления замечаний нужно ли переоткрывать это issue или достаточно оставить комментарий?

**Comment by coursar** [comment]
Лучше переоткрывать, чтобы показать, что вы всё исправили и задача готова к проверке

**Comment by sgv1995** [comment]
Исправил замечания к заданию
